name: Generate Snake Animation

on:
  schedule:
    # Runs at 23:59 UTC every day
    - cron: "59 23 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: sanzayThapa
          outputs: dist/snake.svg

      - name: Upload Snake to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/snake.svg
